- action:
  - alias: Ask if alarm should be enabled
    service: notify.ios_group_notify
    data:
      message: '10pm, alarm not armed. Would you like to turn on the alarm?'
      data:
        push:
          category: arm_alarm
  alias: Alarm Reminder
  condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: disarmed
  id: '1519877524382'
  trigger:
  - at: '22:00'
    platform: time
